### ISSUE TITLE
How to change highlight style?

### ISSUE THREAD

**Issue by CeleritasCelery** [azmelanar/hugo-theme-pixyll#43]
I was trying to switch over the the pixyll theme, but I can't seem to change the highlight style from the default dark style. With other themes I could set 

```toml
[markup]
  [markup.highlight]
    style = "monokailight"
```

And that was enough. But that does not work with Pixyll. I can see a bunch of highlight css in `static/css/highlight` but I don't know how to actually use them. Can you help me understand what I am missing?
